version: "3.7"

services:
  database_clientes:
    image: postgres
    container_name: database_clientes
    restart: always
    ports:
      - 5432:5432
      - 9229:9229
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=clientes
      - POSTGRES_DB=clientes
    volumes:
      - pgdata:/data/postgres
  database_clientes_test:
    image: postgres
    container_name: database_clientes_test
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=clientes
      - POSTGRES_DB=clientes_test
  app:
    build: .
    container_name: api-clientes
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_clientes
    depends_on: 
      - database_clientes

volumes:
  pgdata:
    driver: local
